### ISSUE TITLE
Actualizar evento - No funciona el formulario

### ISSUE THREAD

**Issue by Jumpi96** [Jumpi96/helpo#104]
## Expected Behavior
Debería permitir modificar datos del evento y guardarlos.

## Current Behavior
Carga bien los datos pero no actualiza los campos al editar. No se puede probar guardarlos.

## Possible Solution
Revisar si está bien planteado el formulario. Trabajar similar a otros formularios de edición.

**Comment by GonzaloUlla** [comment]
Yo directamente no puedo editar un evento

**Comment by LuchoGil** [comment]
Tiene problemas con las necesidades tambien. No deja editarlas.
Cuando vuelve para atras, vulve directo al menu de inicio, cuando quiero volver a editar el evento.

**Comment by LuchoGil** [comment]
Al guardar los cambios, la API tira un error 400.

**Comment by LuchoGil** [comment]
A su vez también hay que controlar que ante errores el formulario de modificación, no avisa de los mismo y cierra la pantalla de modificación perdiendo los cambios realizados. Tanto web como mobile. Atención!
