### ISSUE TITLE
Iniciar sesión - Necesita dos clicks para loguear

### ISSUE THREAD

**Issue by Jumpi96** [Jumpi96/helpo#105]
## Expected Behavior
Al hacer click en iniciar sesión debería intentar loguearse y redirigir al menú principal.

## Current Behavior
Al hacer click en iniciar sesión, no pasa nada. Al segundo click se loguea.

## Possible Solution
Trabajar con Promise+redux, para recibir el evento asíncrono de logueo antes de seguir con la carga del menú. Hay algunas librerías para eso.

**Comment by GonzaloUlla** [comment]
Merged PR #253
