### ISSUE TITLE
Mis Colaboraciones - Deja que un mismo voluntario se ofrezca mas de una vez como participante

### ISSUE THREAD

**Issue by LuchoGil** [Jumpi96/helpo#114]
## Expected Behavior

Un voluntario puede ser un solo recurso humano para el evento, como un solo rol.

## Current Behavior

Cuando un voluntario intenta modificar su colaboración, y se quiere volver a ofrecer como recurso humano, lo deja hacer esto libremente.

## Possible Solution

Controlar si un voluntario ya esta siendo algún recurso para el evento que no sea material.

## Steps to Reproduce

1. Mis colaboraciones
2. Editar colaboración
3. Seleccionar alguna función ya seleccionada.
4. Ofrecer

**Comment by Jumpi96** [comment]
Si, pero borra la función anterior. Que es como debería ser. O vos decis que queda ofrecido en ambas funciones?

**Comment by LuchoGil** [comment]
Nono, acumula una nuevo voluntario en esa función, digamos que ocupa otra misma función.
