### ISSUE TITLE
Consultar un Evento - Agregar feature en Mobile

### ISSUE THREAD

**Issue by GonzaloUlla** [Jumpi96/helpo#130]
## Expected Behavior

- Al hacer click en uno de "Mis Eventos" debería acceder a sus datos
## Current Behavior

- Puedo hacer esto yendo a "Consultar eventos" --> "Ver más"
## Possible Solution

Replicar funcionalidad

**Comment by Jumpi96** [comment]
![image](https://user-images.githubusercontent.com/7416778/44788366-3a717100-ab70-11e8-9c51-66ca9c3aeaf7.png)
Y estooo?

**Comment by Jumpi96** [comment]
![image](https://user-images.githubusercontent.com/7416778/44788445-73a9e100-ab70-11e8-8697-0f47ec589863.png)
¿Esto?
