### ISSUE TITLE
Compartir en Redes - Link público a un Evento y a todos los Eventos de una ONG

### ISSUE THREAD

**Issue by GonzaloUlla** [Jumpi96/helpo#136]
## Expected Behavior

Para terminar con la US-070 necesito 2 cosas:
  - Un único super link público de un evento que sea el que vamos a compartir, accesible por usuarios y no usuarios 
  - Lo mismo de arriba pero para todos los eventos de una ONG
  - **Habría que agregar el "Ver más" para consultar los datos de un evento puntual desde NoAuth**
## Current Behavior

  - El link a un Evento difiere entre auth y noAuth
  - Un Usuario no puede entrar al noAuth y  un No-Usuario no puede al auth
  - No está lista la feature de "Ver Eventos" de una ONG

**Comment by Jumpi96** [comment]
Listo. Formato del link: **http://www.helpo.com.ar/#/redirect/evento?id=_ID_**

**Comment by GonzaloUlla** [comment]
y para ONG es: http://www.helpo.com.ar/#/actividades/consultar-eventos?organizacion=ID

**Comment by GonzaloUlla** [comment]
No, no es jajajaja
@Jumpi96 te olvidaste de la mitad del issue hermano, eso te pasa por apurado
Hacé lo mismo para todos los eventos de una ONG con el link: http://www.helpo.com.ar/#/redirect/organizacion?id=ID

**Comment by Jumpi96** [comment]
Mala mia 😘

**Comment by Jumpi96** [comment]
Peeeeero: 
> A la ONG: http://localhost:3000/#/actividades/evento

Ésto no tiene mucho sentido o soy yo? La idea es tener un link publico, que rediriga a los eventos de la ONG. No lo podemos llevar a MisEventos a través de un link publico para mi. No es consistente a mi gusto, yo lo llevaria al mismo lugar que lo lleva al resto de voluntarios, empresas, etc (una lista publica de todos los eventos de esa ONG)

**Comment by GonzaloUlla** [comment]
> Ésto no tiene mucho sentido o soy yo?

Tenés razón, no tiene ningún sentido. Coincido con que es mejor como propusiste vos más abajo

**Comment by GonzaloUlla** [comment]
Formato del link: http://www.helpo.com.ar/#/redirect/ong?id=ID
