### ISSUE TITLE
Consultar eventos - Tiene problemas en mobile

### ISSUE THREAD

**Issue by LuchoGil** [Jumpi96/helpo#139]
## Current Behavior

Tira error y se crashea, no se puede entrar y ver un evento en particular, pero si se listan los eventos existentes.

## Steps to Reproduce

1. Consultar eventos
2. Ver mas en alguno de los eventos

## Environment

- iOS

## Detailed Description

<img width="341" alt="captura de pantalla 2018-08-28 a la s 17 14 32" src="https://user-images.githubusercontent.com/8731248/44748494-4284ce80-aae6-11e8-8677-9743fa5b9391.png">

**Comment by LuchoGil** [comment]
Casi seguro que es porque uso la bd producción y todavia no esta cargado el modelo.

**Comment by Jumpi96** [comment]
Es por eso. No sé si decirte que no es un issue, pero tampoco me gustaría que se pierda algo que tenés duda si anda🤔

**Comment by Jumpi96** [comment]
Si tenés un buen lugar para estas dudas que sean por el entorno, cerralo. Si no fue
