### ISSUE TITLE
Modificar Perfil - No se actualiza imagen de perfil de arribita

### ISSUE THREAD

**Issue by Agianni21** [Jumpi96/helpo#158]
## Expected Behavior

Cuando cambio la imagen de perfil se tendria actualizar instantaneamente el avatar que se muestra en el header de la pagna

## Current Behavior

Hasta que no se hace refresh a la pagina el avatar no cambia

## Steps to Reproduce

1. Cambiar imagen de perfil
2. Guardar cambios
3.
4.

**Comment by LuchoGil** [comment]
Si alguien se pone con esto, de paso ver que mi perfil quede en el lugar que corresponde, y no en el menu del costado izquierdo.

**Comment by GonzaloUlla** [comment]
Reemplazado por #225
