### ISSUE TITLE
Cambiar el mensaje "Error"  cuando el perfil no termino de cargar

### ISSUE THREAD

**Issue by Agianni21** [Jumpi96/helpo#210]
## Current Behavior

Antes de que termine de cargar el perfil aparece un mensaje error feo

## Expected Behavior

Que aparezca algun mensaje de que la pagina se esta cargando

## Steps to Reproduce
1. Ingresar a Mi Perfil
2.
3.
4.

**Comment by GonzaloUlla** [comment]
PR #212
