### ISSUE TITLE
Modelos - Deberíamos tener RubroEmpresa y RubroONG separados

### ISSUE THREAD

**Issue by JuliRios** [Jumpi96/helpo#211]
## Current Behavior
Actualmente el mismo modelo aplica para ambos usuarios, ONG y empresas

## Expected Behavior
Deberían ser dos modelos distintos, los rubros de empresas no aplican para ong

**Comment by GonzaloUlla** [comment]
Falta el frontend...

**Comment by GonzaloUlla** [comment]
Falta solo mobile, lo hace @Jumpi96

**Comment by GonzaloUlla** [comment]
No sé si @Jumpi96 lo hizo en los perfiles mobile o no, falta sólo eso

**Comment by GonzaloUlla** [comment]
Listo
