### ISSUE TITLE
App mobile - Fix RN Google Place Picker

### ISSUE THREAD

**Issue by Jumpi96** [Jumpi96/helpo#218]
## Current Behavior
No se puede utilizar la librería porque no permite buildear APK.

## Expected Behavior
Se puede utilizar la librería.

## Possible Solution
Si no estoy mal, borre completamente la librería de android/, por lo que deberia alcanzar con volver a agregar la librería en el package.json y seguir los pasos que dicen los Docs de la libreria para hacer instalación manual (NO usar link) en Android.

[React Native Google Place Picker](https://github.com/zhangtaii/react-native-google-place-picker)

**Comment by LuchoGil** [comment]
En iOS yo use Pods pero no rompí nada, es mas esa brunch es la de perfiles.
