### ISSUE TITLE
Colaborar - Desde mobile, iniciado el evento, se puede seguir colaborando

### ISSUE THREAD

**Issue by JuliRios** [Jumpi96/helpo#226]
## Current Behavior
Una vez que ha iniciado el evento, como voluntario, puedo seguir colaborando, modificando y eliminando mis colaboraciones previas

## Expected Behavior
Iniciado el evento, no se puede colaborar más, ni modificar colaboraciones ni eliminarlas

## Steps to Reproduce
1. Mis colaboraciones
2. Selección de un evento iniciado/finalizado
3. Comentar
4. Si no comenté antes, comento y vuelvo a reproducir los pasos
5. Colaborar
6. Selección de una necesidad o función
7. Modificar/Eliminar

**Comment by Jumpi96** [comment]
Working
