### ISSUE TITLE
Inicio Evento - A Voluntarios y empresas le llegan dos mails de inicio

### ISSUE THREAD

**Issue by JuliRios** [Jumpi96/helpo#227]
## Current Behavior
Tanto a voluntarios como empresas le llegan dos mails iguales de inicio del evento

## Expected Behavior
Debe llegar solo un mail de inicio de evento, como a las organizaciones

**Comment by GonzaloUlla** [comment]
Esto hoy en la exposición de pósters anduvo bien, por favor revisar

**Comment by GonzaloUlla** [comment]
Lo acabo de revisar y tenes razon, asi que working...
