### ISSUE TITLE
Ver Álbum - No se visualiza el álbum

### ISSUE THREAD

**Issue by JuliRios** [Jumpi96/helpo#229]
## Current Behavior
Al seleccionar la opción "Ver Álbum", como voluntario o empresa, no se visualiza el mismo. En cambio, se redirige el Home

## Expected Behavior
Al seleccionar la opción "Ver Álbum" se debe visualizar el álbum del evento

## Steps to Reproduce
1. Mis colaboraciones
2. Comentar
3. Ver Álbum

1. Organizaciones
2. Ver Perfil
3. Ver eventos organizados
4. Ver más en un evento
5. Ver Álbum

**Comment by Jumpi96** [comment]
Que onda esto? @Agianni21 @JuliRios
