### ISSUE TITLE
Editar evento - No se editan los campos

### ISSUE THREAD

**Issue by JuliRios** [Jumpi96/helpo#235]
## Current Behavior
Al editar un evento, no se guardan los cambios. Y aparece otro evento creado denominado "INCOME" (undefined)

## Expected Behavior
Se deben guardar los datos modificados de un evento

## Steps to Reproduce
1. Sign in como ong
2. Mis eventos
3. Editar evento
4. Guardar cambios

**Comment by Jumpi96** [comment]
Fixed
