### ISSUE TITLE
Consultar colaboraciones - El botón Volver del modal no vuelve

### ISSUE THREAD

**Issue by JuliRios** [Jumpi96/helpo#237]
## Current Behavior
En consultar colaboraciones, al guardar cambios se levanta un modal con la opción Volver. Apretado ese botón, se sigue en la misma pantalla.

## Expected Behavior
El botón Volver debería volver a Mis eventos

## Steps to Reproduce
1. Sign in como ong
2. Mis eventos
3. Consultar colaboraciones
4. Guarda cambios
5. Volver

**Comment by LuchoGil** [comment]
Same on mobile.

**Comment by LuchoGil** [comment]
Mistake, i will open a new issue for other problem.
