### ISSUE TITLE
Registrar evento - Seleccionar ubicación no abre el mapa

### ISSUE THREAD

**Issue by JuliRios** [Jumpi96/helpo#238]
## Current Behavior
Al registrar o modificar un evento, el botón Seleccionar ubicación no hace nada

## Expected Behavior
El botón Seleccionar ubicación debería mostrar el mapa de Google

## Steps to Reproduce
1. Sign in como ong
2. Nuevo evento
3. Seleccionar ubicación

**Comment by LuchoGil** [comment]
#218 check after solve this issue.

**Comment by Jumpi96** [comment]
Es el mismo issue, lo uno a la 218
