### ISSUE TITLE
Suscribirme a ONG - Al crear un nuevo evento la ong, no llega mail al voluntario

### ISSUE THREAD

**Issue by JuliRios** [Jumpi96/helpo#239]
## Current Behavior
No llega mail al voluntario cuando la ong crea un evento 

## Expected Behavior
Como voluntario suscripto a la ong, debe llegarle un mail cada vez que la ong crea un evento

**Comment by GonzaloUlla** [comment]
Esto más que un issue es una feature que le faltó a @Agianni21 
Lo puede hacer él o yo

**Comment by GonzaloUlla** [comment]
supuestamente hecho en PR #297 
falta probarlo para cerrar el issue

**Comment by GonzaloUlla** [comment]
Ya lo probe, cierro
