### ISSUE TITLE
Contactos - No deja crear un evento sin contactos

### ISSUE THREAD

**Issue by LuchoGil** [Jumpi96/helpo#244]
## Current Behavior

Intentando crear un evento sin contacto/s tira error " No puede ingresar un contacto sin nombre" "Debe ingresar un mail valido"

## Expected Behavior

Que se pueda crear un evento sin contacto/s.
Que por defecto no aparezca la opción para crear un contacto, si se desea que se agregue.

## Steps to Reproduce
1. Crear evento sin crear contacto
2. Guardar evento

**Comment by Jumpi96** [comment]
Working
