### ISSUE TITLE
Agregar voluntario - No deja cargar un voluntario

### ISSUE THREAD

**Issue by LuchoGil** [Jumpi96/helpo#248]
## Current Behavior

Apenas creas el evento y tratas de cargar voluntarios seleccionando función, cantidad y descripción, tira un error del tipo "Hubo un problema al cargar.." o algo asi, pero si guardas el evento y vas a modificarlo te deja agregar voluntarios.
## Expected Behavior

Que te deje agregar voluntarios (funciones) siempre.
## Steps to Reproduce
1. Crear evento
2. Cargar voluntarios
3. Editar evento

**Comment by Jumpi96** [comment]
Intenté repetirlo pero no fallo
