### ISSUE TITLE
Eliminar propuesta de patrocinio- No se elimina propuesta en listado de propuestas del evento

### ISSUE THREAD

**Issue by LuchoGil** [Jumpi96/helpo#250]
## Current Behavior

Al realizar una propuesta y eliminarla, no se actualiza dicha propuesta en el listado de propuestas.

## Expected Behavior

Que cuando se elimine por completo una propuesta o en otro caso se llegue a este estado eliminando todos los subitems, esta propuesta no se le muestre más a la ONG.
Que cuando se haya eliminado la propuesta y la Empresa desea realizar una una nueva propuesta sobre el mismo evento dicha propuesta se muestre como una nueva chequeando que no haya propuestas anteriores y poniendo la fecha actual dela nueva propuesta y no la de la propuesta vieja (como actualmente pasa).

## Steps to Reproduce
1. Generar propuesta
2. Consultar propuesta (ONG)
3. Eliminar propuesta (todos los items)
4. Consultar propuestas (ONG)
5. Generar una nueva propuesta sobre el mismo evento
6. Consultar propuestas (ONG)

**Comment by Jumpi96** [comment]
Working
