### ISSUE TITLE
Registrar necesidades materiales - Otros no registra correctamente

### ISSUE THREAD

**Issue by LuchoGil** [Jumpi96/helpo#252]
## Current Behavior

Al seleccionar un material del tipo "Otros" agregando la descripción correspondiente, registra cualquier material en el listado de necesidades.
## Expected Behavior

Que se registre otro material bajo ese tipo y no cualquier tipo.
## Steps to Reproduce
1. Registrar necesidad material
2. Seleccionar tipo: "Otros"

## Detailed Description

En el caso de seleccionar funciones no pasa esto, "Otras" dentro de las funciones no se guardan mal.
Como un agregado a esto, podría ser que cuando el tipo seleccionado sea "Otro" para necesidades materiales, no se muestre el subtipo ya que no hay subtipos para Otros, sino que podría mostrarse como funciones, solo para este caso, queda mejor y no genera confusiones.

**Comment by LuchoGil** [comment]
No puedo decir si pasa lo mismo en mobile.

**Comment by Jumpi96** [comment]
No se si estoy mal pero no se si la mejor solución es que "Otros" no tenga subtipo porque dentro de ahi podria haber elementos definidos pero que no hayamos categorizado (y ademas desarma el modelo nuestro sin mucho beneficio). Si no, agrega un recurso Otros que sea el unico recurso de la categoria Otros
