### ISSUE TITLE
Consultar eventos - No auth vuelve a inicio cuando queres colaborar en un evento

### ISSUE THREAD

**Issue by LuchoGil** [Jumpi96/helpo#254]
## Current Behavior

Al no esta logueado, consultar un evento y tratar de colaborar en el mismo, al apretar colaborar te devuelve a la pantalla de inicio.
## Expected Behavior

Que al oprimir ese botón te de la opción de ir a loguearte para despues si queres recién participar, un modal sencillo, o que ese botón desaparezca para no auth. Voto más por la  primera.
## Steps to Reproduce
1. No auth
2. Eventos
3. Ver mas
4. Colaborar

**Comment by Jumpi96** [comment]
Working
