### ISSUE TITLE
Ortografía - Corregir mensajes a los usuarios

### ISSUE THREAD

**Issue by GonzaloUlla** [Jumpi96/helpo#290]
## Current Behavior

* "Espere unos segundos, la pagina se esta cargando..."
* "Subscripcion"
* "Estadisticas"
* etc.
## Expected Behavior

* "Espere unos segundos, la **página** se **está** cargando..."
* "**Suscripción**"
* "Estad**í**sticas"
* etc.

## Possible Solution

Pasarle algún corrector ortográfico al código o corregir los errores por todos lados.

**Comment by GonzaloUlla** [comment]
### Corregidos al 6/10/2018
* Imágenes
* Álbum
* Colaboración
* Participación / participó
* Suscripción
### Tips (cosas que buscar para encontrar errores):
* Cargando
* Text
* ContainerHeader
* Título / title
* Desea
## IMPORTANTE
* No meter más errores ortográficos programando
* Cuando vayamos encontrando nuevos errores, si no los podemos corregir en el momento, ponerlos en este issue (no cerrar el issue)

**Comment by Jumpi96** [comment]
Cosas que faltan:
- Validar campos (en ong/empresas no valida)
- Cambiar orden de campos ModificarPerfilOrganizacion (salen distintos a la consulta)

**Comment by GonzaloUlla** [comment]
Otros hermosos hallazgos mal escritos:
* Válido
* Teléfono
