### ISSUE TITLE
Consultar organizaciones - No se puede ver el perfil

### ISSUE THREAD

**Issue by JuliRios** [Jumpi96/helpo#293]
## Current Behavior
Desde Consultar Organizaciones, no se puede ver el perfil de alguna ong seleccionada

## Expected Behavior
Se debe poder ver el perfil de la ong mediante la funcionalidad Consultar Organizaciones

## Steps to Reproduce
1. Consultar organizaciones
2. Ver Perfil

**Comment by GonzaloUlla** [comment]
Probado hoy desde master, esta andando, no en produccion
No cierro todavia

**Comment by Jumpi96** [comment]
Fixed
