### ISSUE TITLE
Suscripción ONG - No funciona

### ISSUE THREAD

**Issue by JuliRios** [Jumpi96/helpo#294]
## Current Behavior
Desde mobile, no funciona la suscripción de un voluntario a una ong

## Expected Behavior
Los voluntarios tienen que poder suscribirse a una ong

## Steps to Reproduce
1. Consultar Organizaciones
2. Suscribirse

**Comment by GonzaloUlla** [comment]
Segun el Bore lo arreglo en #297, no cierro el issue hasta que alguien no lo pruebe

**Comment by GonzaloUlla** [comment]
Probado, cierro
