### ISSUE TITLE
Ver Colaboraciones - No se listan todas ni se puede scrollear

### ISSUE THREAD

**Issue by JuliRios** [Jumpi96/helpo#295]
## Current Behavior
Al seleccionar "Ver Colaboraciones" de un evento, no se listan todas las colaboraciones ni se puede scrollear para abajo

## Expected Behavior
Se deben listar todas las colaboraciones correspondientes y se puede scrollear para abajo

## Steps to Reproduce
1. Mis eventos
2. Ver más
3. Ver Colaboraciones

**Comment by GonzaloUlla** [comment]
Done
