### ISSUE TITLE
Mails Participación - Latitud y longitud no definidas

### ISSUE THREAD

**Issue by JuliRios** [Jumpi96/helpo#300]
## Current Behavior
En el mail que le llega al voluntario por la PARTICIPACIÓN en un evento, los datos latitud y longitud aparecen como "No definida"

## Expected Behavior
Deben aparecer las coordenadas de latitud y longitud

## Steps to Reproduce
1. Eventos
2. Seleccionar evento
3. Colaborar con función en el evento

**Comment by GonzaloUlla** [comment]
Se arregló en la PR #298 
![image](https://user-images.githubusercontent.com/26656871/46646358-3a499580-cb60-11e8-9a45-9de4beb90000.png)
