### ISSUE TITLE
Mail Respuesta Propuesta - Respuesta con tag html

### ISSUE THREAD

**Issue by JuliRios** [Jumpi96/helpo#301]
## Current Behavior
Dentro del mail, en el apartado "Respuesta", se visualiza un tag html (<b></b>), además de la respuesta Aceptada o Rechazada

## Expected Behavior
Solo se debe visualizar la respuesta Aceptada o Rechazada

![mail propuesta aceptada](https://user-images.githubusercontent.com/13774428/46578929-e1062880-c9de-11e8-9373-0634bb39beaa.PNG)

**Comment by Jumpi96** [comment]
Working
