### ISSUE TITLE
Mail Respuesta Propuesta - Al enviar este mail se envía otro erróneo

### ISSUE THREAD

**Issue by JuliRios** [Jumpi96/helpo#302]
## Current Behavior
A la empresa, al llegarle el mail de "respuesta a propuesta" también le llega otro mail de "nueva propuesta"

## Expected Behavior
A la empresa, solo le debe llegar el mail de "respuesta a propuesta" y el de "nueva propuesta" debe llegarle a la ONG, que actualmente no le llega

![bug mails propuesta](https://user-images.githubusercontent.com/13774428/46578960-815c4d00-c9df-11e8-8fea-7106932d70de.PNG)

**Comment by Jumpi96** [comment]
No lo logro repetir. Cuando actualicemos production, vemos si se mantiene @JuliRios

**Comment by LuchoGil** [comment]
![image](https://user-images.githubusercontent.com/8731248/48036872-e7f09a00-e148-11e8-8271-381db17d46bd.png)
 Uno de los mails eso va a la ONG y otro si a la Empresa. Validar bien. WEB Y MOBILE

**Comment by GonzaloUlla** [comment]
WIP
