### ISSUE TITLE
Consultar evento - No muestra ubicación 

### ISSUE THREAD

**Issue by LuchoGil** [Jumpi96/helpo#312]
## Current Behavior

En ningún lado se puede visualizar la ubicación del evento.
## Expected Behavior

Al consultar un evento, poder visualizar la ubicación.
## Steps to Reproduce
1. Eventos
2. Ver más

## Possible Solution

Puede que se deba a la librería que nos está funcionando en mobile.

**Comment by GonzaloUlla** [comment]
Increíble que no esté andando esto pero cierto, acá la captura desde el perfil de un Voluntario, haciendo click en "Ver más" de un Evento:
![image](https://user-images.githubusercontent.com/26656871/46646586-5568d500-cb61-11e8-9337-cea6cbeff4c4.png)
