### ISSUE TITLE
Ir atrás Web - "Volver" no funciona

### ISSUE THREAD

**Issue by GonzaloUlla** [Jumpi96/helpo#314]
**_ESTE ES EL ÚNICO ISSUE PARA CASOS EN LOS QUE IR ATRÁS WEB NO FUNCIONE_**
## Current Behavior

Al apretar "Volver" (Go back) en el browser, Helpo Web no se comporta como debería estando en las pantallas:
1. Ver álbum
2. Detalle colaboraciones
3. Eliminar evento
## Expected Behavior

Respectivamente, cada pantalla debería volver a:
1. "Ver más" del Evento.
2. Ídem 1
3. "Mis eventos"
## Possible Solution

Bore: react-router-dom VS history.push
JPL: Redux, magia negra, no sé cómo, excusa excusa, llanto llanto

**Comment by LuchoGil** [comment]
En mobile, Ver albúm, te lleva directamente al Home cuando apretas volver atrás. Debería llevarte a la vista del evento.

**Comment by LuchoGil** [comment]
Eliminar AS te lleva al home en WEB, en mobile no. Además cuando se vea eso ver el issue #413 tanto WEB COMO MOBILE para enviar notificaciones a los inscriptos.
