### ISSUE TITLE
Ir atrás Mobile - "Volver" no funciona

### ISSUE THREAD

**Issue by GonzaloUlla** [Jumpi96/helpo#315]
**_ESTE ES EL ÚNICO ISSUE PARA CASOS EN LOS QUE IR ATRÁS MOBILE NO FUNCIONE_**
## Current Behavior

Al apretar "Volver" (flecha que apunta a la izquierda en la esquina superior izquierda de la App o botón Go back del celular), Helpo Mobile no se comporta como debería estando en las pantallas:
1. Ver álbum
2. Mi perfil
3. Home
## Expected Behavior

Respectivamente, cada pantalla debería volver a:
1. "Ver más" del Evento.
2. Podría dejar el side-pannel abierto, es un enhancement.
3. Cerrar la app.
## Possible Solution

Bore: react-router-dom VS history.push
JPL: Redux, magia negra, no sé cómo, excusa excusa, llanto llanto

**Comment by LuchoGil** [comment]
Lo mas prioritario es el de "Ver albúm"
