### ISSUE TITLE
Compartir todos los eventos - Desaparecieron los botones en Mobile

### ISSUE THREAD

**Issue by GonzaloUlla** [Jumpi96/helpo#320]
## Current Behavior

Al acceder a la lista de Eventos de una ONG, no aparece más el componente con los 4 botones para compartir todos sus eventos en Redes Sociales. Antes aparecía.

## Expected Behavior

Ver los botones para compartir en Redes al final de la lista de Eventos, permitiendo compartir **todos los eventos de una ONG** desde Mobile.
## Steps to Reproduce
1. Ver perfil de una ONG
2. Ver eventos
3. Scrollear hasta abajo
4. ¿Botones para compartir?

**Comment by LuchoGil** [comment]
No solo que desaparecieron de ahí, sino que también de la opción "Actividades sociales" donde se consultan todas las actividades de Helpo, devuelvanme los botoncitos de compartir pls.

**Comment by LuchoGil** [comment]
Viendo un poco más, capaz que este mal en el comentario anterior, porque pensé que en algún momento dejábamos compartir TODOS los eventos de Helpo. Pero lo mismo, el problema original del Issue, no esta resuelto. @Jumpi96

**Comment by GonzaloUlla** [comment]
> No solo que desaparecieron de ahí, sino que también de la opción "Actividades sociales" donde se consultan todas las actividades de Helpo, devuelvanme los botoncitos de compartir pls.

Esto nunca fue así ni va a serlo
