### ISSUE TITLE
Ver eventos de ONG - Al ir atrás se borra el filtro y se mezclan eventos

### ISSUE THREAD

**Issue by JuliRios** [Jumpi96/helpo#324]
## Current Behavior
Al dirigirse al perfil de una ong y ver los eventos organizados se muestran correctamente los mismos. Si selecciono un evento y luego vuelvo atrás, el filtro por ong se pierde y se visualizan eventos de otras ong

## Expected Behavior
Al volver atrás, se debe volver solo a los eventos de la ong para la cual estoy viendo el perfil

## Steps to Reproduce
1. Organizaciones
2. Ver perfil
3. Ver eventos organizados
4. Seleccionar evento
5. Volver atrás

**Comment by LuchoGil** [comment]
Something went wrong here...
Consultas todas las actividades sociales, ver más en una, volvés para atrás en una y te muestra solamente las AS de ONG Helpo. Flashero pero creo que esta todo de la mano...
