### ISSUE TITLE
Eliminar colaboración - Luego de entregar, se elimina todo lo donado

### ISSUE THREAD

**Issue by JuliRios** [Jumpi96/helpo#340]
## Current Behavior
Colaborar, entregar, re-colaborar, eliminar -> elimina todas las colaboraciones en esa necesidad, incluso las ya entregadas

## Expected Behavior
Las colaboraciones ya entregadas no se deben poder eliminar

## Steps to Reproduce
1. Como voluntario, colaborar
2. Como ONG, marcar colaboración como entregada
3. Como voluntario volver a colaborar en la misma necesidad
4. Como voluntario, eliminar colaboración

**Comment by LuchoGil** [comment]
En mobile esto no funciona con la misma lógica y se rompe de igual manera. Si yo edito en mobile y colaboró con menos de lo que hay entregado me deja, hay que hacerlo para mobile también.

**Comment by LuchoGil** [comment]
![image](https://user-images.githubusercontent.com/8731248/47972764-15244600-e07e-11e8-90ae-1d7be6e2e34e.png)
 Eso mismo en mobile. @Agianni21

**Comment by Agianni21** [comment]
No es parte del issue, correctivo a lucho, se cierra con #419
