### ISSUE TITLE
Propuesta sobre una campaña - Spam de mail con cada uno de lo que colaboro

### ISSUE THREAD

**Issue by LuchoGil** [Jumpi96/helpo#358]
## Current Behavior

Al no tener un boton global para guardar propuestas o colaboraciones, cada vez que agregas omodificas una colaboracion en una capaña, te llega unmail, cuando lo correcto seria que te llegue un mail con TODO lo que colaboras. Estamos llenando de mails a las empresas y no se si a los voluntarios con eso.
## Expected Behavior

Un solo mail con el detalle de lo que colaboras, junto con un boton guardar por mas que sea bobo.
## Steps to Reproduce
1.Realizar una porpuesta de muchas cosas y modificarlas, se vera como llegan muchos mails.

![imagen](https://user-images.githubusercontent.com/8731248/47458081-22545180-d7af-11e8-8d8d-1c8bd78c60b8.png)

**Comment by GonzaloUlla** [comment]
WIP

**Comment by GonzaloUlla** [comment]
Empresas no reciben mas mails cuando CREAN Colaboraciones o Participaciones, si cuando las editan o eliminan
