### ISSUE TITLE
Mail de suscripciones - ONG crea evento y desde la redirección del mail la pantalla queda cargando

### ISSUE THREAD

**Issue by LuchoGil** [Jumpi96/helpo#368]
## Current Behavior

Cuando un voluntario se suscribe a una ONG y esta crea una AS, el mail que llega avisando al voluntario suscrito, contiene un botón que lo redirige al evento de helpo, pero si el voluntario no se encuentra logueado, esta pantalla queda cargando y nunca le muestra el evento, en cambio si esta logueado si se la muestra bien.
## Expected Behavior

El botón del mail redireccione bien y el usuario sin esta logueado pueda consultar el evento.

Tocas el boton Ir a Evento (que debería decir Ir a **Actividad**)
![image](https://user-images.githubusercontent.com/8731248/47594886-cc6cde80-d953-11e8-8be1-86935f3597ff.png)

Y se queda cargando en esta pantalla. 
![image](https://user-images.githubusercontent.com/8731248/47594876-c4ad3a00-d953-11e8-88e2-e630e6f195c7.png)

**Comment by Jumpi96** [comment]
Fixed en master hace varios dias.
