### ISSUE TITLE
Cambiar Evento por Actividad Social o Actividad, según corresponda

### ISSUE THREAD

**Issue by LuchoGil** [Jumpi96/helpo#370]
## Current Behavior

En muchísimos lugares aparece la palabra Evento y no corresponde. Reportes, Pantallas, etc, a medida que vaya detectando los agrego a este ISSUE. 
## Expected Behavior

Que aparezca Activdad o Actividad en vez de Evento, en los lugares que corresponda.

Lugares donde pasa esto:
- Reporte de colaboraciones sobre una actividad social.

**Comment by JuliRios** [comment]
Repetido #338
