### ISSUE TITLE
Registrar necesidades - Categoría "Otro" se convierte en alimento

### ISSUE THREAD

**Issue by LuchoGil** [Jumpi96/helpo#379]
## Current Behavior

Titulo, cuando guaramos necesidades habiendo seleccionado "Otro"  como categoria de alguna necesidad material, se guarda esta categoría como alimento.
## Expected Behavior

Se guarde como categoria "Otro"

![image](https://user-images.githubusercontent.com/8731248/47611514-ec7cca80-da45-11e8-9488-52b050918410.png)

**Comment by Jumpi96** [comment]
Esto es por que "Otros" no tiene recursos. Creale a produccion un recurso "Otros" o "----------" o " - " o lo que mejor quede (personalmente, prefiero "Otros")
