### ISSUE TITLE
Colaborar en una actividad - Volver atrás te lleva a Mis Colaboraciones

### ISSUE THREAD

**Issue by LuchoGil** [Jumpi96/helpo#423]
## Current Behavior

Titulo.
## Expected Behavior

Te debe llevar a la actividad en cuestión
## Steps to Reproduce
1. Como voluntario colaborar en una actividad
2. Volver atras
3. Te muestra todas las actividades

**Comment by Jumpi96** [comment]
Podemos negociar que te mande a MisColaboraciones?

**Comment by Jumpi96** [comment]
ConsultarEvento no es "independiente", le tengo que pasar un objeto evento que no tengo, agregar llamadas a la api y demas

**Comment by LuchoGil** [comment]
Dejalo como esta de momento.
