### ISSUE TITLE
Registrar evento - Agregar contacto es obligatorio

### ISSUE THREAD

**Issue by JuliRios** [Jumpi96/helpo#47]
Al seleccionar el botón Agregar Contacto, se habilitan nuevos campos para cargar otro contacto. Esta segunda carga, sin embargo, no debería ser obligatoria ya que si no cargo un segundo contacto e intento guardar, salta un mensaje de error:

"No puede ingresar un contacto sin nombre
Debe ingresar un mail o un telefono"

Ante este mensaje, la única alternativa es seleccionar Remover Contacto, para que se eliminen los campos del contacto 2 que nunca tuve intención de registrar.

**Comment by luchogil96** [comment]
Resuelto con el nuevo componente para carga de contactos para los eventos.
