### ISSUE TITLE
Cambio de logo de Helpo

### ISSUE THREAD

**Issue by Jumpi96** [Jumpi96/helpo#480]
## Expected Behavior
Como parte de Helpo, quiero tener el nuevo logo como imagen de Helpo.

Se debe cambiar el logo en los siguientes lugares:
- Pestaña del navegador - https://i.imgur.com/YF0qXfu.png
- Header de la página de inicio como visitante - https://i.imgur.com/RlfCbmg.png
- Página de login - https://i.imgur.com/RlfCbmg.png
- Página de registro - https://i.imgur.com/S8EvgST.png
- Header de la página de inicio como voluntario / ong - https://i.imgur.com/zs9x9dq.png
- Imágenes de página de inicio como visitante
- Imágenes de página de inicio como voluntario / ong

**Comment by Jumpi96** [comment]
Necesitamos los assets para cambiar esto y ponerlo RFW.

**Comment by GonzaloUlla** [comment]
Dónde carajo hay que cambiar el logo @JuliRios

**Comment by GonzaloUlla** [comment]
Te salvaste de esta @Jumpi96

**Comment by GonzaloUlla** [comment]
@JuliRios Sigo sin poder cambiar esto, necesito los assets como están en [Google Drive/Helpo/05.Design/00.Nuevo Logo/0. Pedido/](https://drive.google.com/drive/folders/1hroxrI-TRFEF-oVlXBoa32VyohXxg0Q0)
