### ISSUE TITLE
El acceso a Instagram no funciona

### ISSUE THREAD

**Issue by Jumpi96** [Jumpi96/helpo#484]
## Current Behavior
El acceso a Instagram redirecciona a @helpoconsultas.

## Expected Behavior
El acceso a Instagram debe redireccionar a @helpo.oficial.

## Steps to Reproduce
1. Entrar a Helpo web.
2. Intenta ingresar a la cuenta de Instagram.

**Comment by GonzaloUlla** [comment]
Ídem #485. Cierro ambos campeón de la automation en GitHub @Jumpi96
