### ISSUE TITLE
Modificar imagen de página de inicio

### ISSUE THREAD

**Issue by JuliRios** [Jumpi96/helpo#491]
## Expected Behavior
Como visitante del sitio, quiero visualizar como imagen principal del sitio la siguiente:
https://drive.google.com/drive/folders/1KpJemZgfCKE4TooaT-c_2w2CiSZOD80P
Nombre del archivo: Placas web-3.jpg

## Description
- Sacar carrousel de imágenes
- Dejar solo una imagen de forma permanente

**Comment by GonzaloUlla** [comment]
@JuliRios no voy a cambiar esto hasta que no pueda cambiar el logo #480 
Pasame el asset como una ruta a nuestro Drive, sino 0 trazabilidad a través de un link a imgur

**Comment by JuliRios** [comment]
Quería evitar poner rutas a nuestro Drive. Pero listo, ya lo modifiqué :)

**Comment by GonzaloUlla** [comment]
No debería haber drama si tenemos bien configurados los permisos de acceso

**Comment by GonzaloUlla** [comment]
@JuliRios saco lo de los feeds de acá y lo pongo en: #496
