### ISSUE TITLE
No se visualiza la imagen de perfil guardada

### ISSUE THREAD

**Issue by JuliRios** [Jumpi96/helpo#495]
## Expected Behavior
Al editar mi perfil como voluntario, selecciono e ingreso mi imagen de perfil y, una vez guardados los cambios, visualizo mi imagen de perfil correctamente.

## Current Behavior
Al editar mi perfil como voluntario, selecciono e ingreso mi imagen de perfil y, una vez guardados los cambios, no visualizo mi imagen de perfil. En su lugar, visualizo la palabra avatar.

## Steps to Reproduce

1. Inicio sesión como voluntario
2. Selecciono la opción Mi Perfil
3. Selecciono la opción Modificar Datos
4. Selecciono la opción Seleccionar archivo.
5. Selecciono imagen de perfil.
6. Selecciono la opción Guardar Cambios.

## Detailed Description
https://i.imgur.com/YH5Lrft.png

**Comment by GonzaloUlla** [comment]
Listo! Me cago en Bore Temporada 4 Episodio 33
![image](https://user-images.githubusercontent.com/26656871/82168272-ca030a00-9894-11ea-9eec-31d8ecd6b895.png)
