### ISSUE TITLE
Como Voluntario, quiero enterarme del listado de actividades sociales publicadas para poder contribuir a ellas

### ISSUE THREAD

**Issue by PauPonte** [Jumpi96/helpo#521]
Establecer un mecanismo para el Corto Plazo.
Evaluar y establecer un mecanismo para el Largo Plazo.

**Comment by GonzaloUlla** [comment]
@PauPonte https://www.mountaingoatsoftware.com/agile/user-stories

**Comment by GonzaloUlla** [comment]
Sugiero hacer web mailing con un newsletter del cual podamos sacar analíticas, usando Zoho o HubSpot @PauPonte @GregoPaez
