### ISSUE TITLE
SignUp - Mas responsivo para usuario (UX)

### ISSUE THREAD

**Issue by Agianni21** [Jumpi96/helpo#54]
Al registrar un usuario que se cambie de pantalla o avise si fallo.

**Comment by GonzaloUlla** [comment]
-  Limpiar errores y campos cuando se cambia de pestañas (Voluntario -> ONG)

**Comment by luchogil96** [comment]
Limpio los errores, los campos creo que esta bueno que se mantengan, por ahi empezaste a escribir en algún otro usuario que no querias crear, pero los datos que pusiste estaban bien y si te quedan guardados te ahorras de volver a escribirlos.
