### ISSUE TITLE
Modificar perfil de ONG no redirige a la consulta del perfil

### ISSUE THREAD

**Issue by JuliRios** [Jumpi96/helpo#540]
## Expected Behavior
Luego de modificar el perfil de una ONG, se visualiza un mensaje de éxito y el "Aceptar" del mismo redirige a la consulta del perfil.

## Current Behavior
Luego de modificar el perfil de una ONG, se visualiza un mensaje de éxito y el "Aceptar" del mismo no redirige a ningún lado, imposibilitando cualquier otra acción que se desee realizar.

## Steps to Reproduce
1. Loguearse como ONG
2. Mi Perfil
3. Modificar algún dato del perfil
4. Guardar cambios
5. Presionar botón Aceptar

**Comment by GonzaloUlla** [comment]
Closed in #539
