### ISSUE TITLE
As an analyst, I want to send emails to a DL of users so I can communicate with them

### ISSUE THREAD

**Issue by GonzaloUlla** [Jumpi96/helpo#546]
## Expected Behavior

- Use Zoho to automatically email all volunteers/NGOs

## Current Behavior

- Manually set all email addresses

**Comment by GonzaloUlla** [comment]
Check Drive, Marketing, Importar contactos.
To do: Automate ETL

**Comment by PauPonte** [comment]
No pudimos cargarlos

**Comment by GonzaloUlla** [comment]
No tenés que cargar nada, probá seleccionar y enviar correo masivo con los contactos que ya están cargos. Si anda OK, cerrá el issue @PauPonte
