### ISSUE TITLE
SignUp - Avisar si usuario ya está registrado

### ISSUE THREAD

**Issue by Agianni21** [Jumpi96/helpo#55]
Título

**Comment by GonzaloUlla** [comment]
Avisar:
-  Si ya hay un usuario registrado con ese mail (falla)
-  Si registró correctamente
-  Si hubo un error al registrar

**Comment by LuchoGil** [comment]
@Jumpi96  @Agianni21  API please!!!!

**Comment by GonzaloUlla** [comment]
Done pero, falta:
  - Hacer en mobile
  - Mejorar cuando ya existe un usuario que no vuelva al dashboard

**Comment by LuchoGil** [comment]
@JuliRios te podes encargar de mejorar, haciendo funcionar el ModalRegistroExitosio, y si te animas crear un nuevo modal para el registro "no exitoso". Me podes pedir ayuda para cualquier cosa.
