### ISSUE TITLE
Registrar evento - Reubicar campo Rubro

### ISSUE THREAD

**Issue by JuliRios** [Jumpi96/helpo#66]
Para mantener todos los campos en una sola columna, se debe colocar el campo Rubro del evento debajo del campo Nombre evento.

**Comment by luchogil96** [comment]
Resuelto con el componente nuevo de contactos y los labels de inicio y fin de evento.

**Comment by GonzaloUlla** [comment]
Buenísimo @luchogil96, la próxima para mayor trazabilidad, cuando commitees, hacelo:
`git commit -m "Issue #66: Mensaje del commit"`

El # con numero de commit hace que podamos ver el commit desde acá
