### ISSUE TITLE
SignUp - Mail no debe ser Case Sensitive

### ISSUE THREAD

**Issue by GonzaloUlla** [Jumpi96/helpo#77]
## Expected Behavior

  - Al registrar, el campo mail se debería pasar todo toUpperCase o toLowerCase
  - Deberíamos hacerlo en **front**, en la **api** y en **mobile**
  - Tanto *dirección* de mail como *dominio* (el campo entero) se debería parsear para no ser Case Sensitive
## Current Behavior

  - GonUlla@hotmail.com
  - gonulla@HotMail.com
  - gonulla@hotmail.com

Son 3 usuarios distintos, cuando debería ser el mismo

**Comment by LuchoGil** [comment]
@Jumpi96 como lo resolvemos, lo manejo yo desde el front? o desde el back?

**Comment by GonzaloUlla** [comment]
No llegan las notificaciones de esto hermano, hablale por whatsapp

**Comment by LuchoGil** [comment]
@JuliRios aca abría que hablar con @Jumpi96 para ver que solucion vamos a adoptar, si manejarlo por el front, por el back o por ambos.
