### ISSUE TITLE
Diseño gráfico - Tamaño de imágenes y pie de página

### ISSUE THREAD

**Issue by GonzaloUlla** [Jumpi96/helpo#84]
## Expected Behavior

  - El tamaño de las fotos de Home 1 y Home 2 debería ser responsive y ajustarse al tamaño de pantalla.
  - En el pie de página debería decir algo como: "helpo.com.ar - 2018"
## Current Behavior

  - Las fotos Home 1 y Home 2 son muy chicas.
  - El pie de página dice "Core UI"

**Comment by GonzaloUlla** [comment]
- https://developers.google.com/speed/pagespeed/insights/?url=helpo.com.ar&tab=desktop
  - https://developers.google.com/speed/docs/insights/OptimizeImages
Por ahi sirve para hacer mas rapida la carga, por ahi le baja la calidad a la foto y queda horrible, por ahi es tarde y estoy hablando al pedo

**Comment by GonzaloUlla** [comment]
![image](https://user-images.githubusercontent.com/26656871/43817659-faa1afec-9ab0-11e8-9916-ec85d0e473ca.png)
Las llamadas a maps.googleapis.com son las que mas demoran, deberiamos ver donde hacerlas o tratar de setearles el maximo tiempo posible para que el browser las mantenga cacheadas.

**Comment by LuchoGil** [comment]
@JuliRios yo creo que de esto entendes mas que yo. Con un rato de reniegue lo sacas. Lee comentario anteriores.

**Comment by GonzaloUlla** [comment]
Replaced by issue #93
