### ISSUE TITLE
SignUp - Bug: modal se abre antes de petición http

### ISSUE THREAD

**Issue by GonzaloUlla** [Jumpi96/helpo#88]
## Expected Behavior

Primero ir contra la api, registrar el usuario (hacer el sign up), evaluar el response.status_code que tira la api y en función de eso mostrar el modal de bienvenida al usuario que recién se registra.
## Current Behavior

Ahora se abre el modal primero y después tira la petición a la API

**Comment by LuchoGil** [comment]
Voy a aprovechar para poner un modal mas lindo, pero necesito ayuda con ruteo.
Voy a ver si dejo una solución provisoria.

**Comment by LuchoGil** [comment]
@JuliRios encargate de que ande el lindo Modal con Ruteo, tambien hay que hacer un nuevo modal para cuando no es exitoso.
