### ISSUE TITLE
Consultar perfil - Mostrar usuario al clickear foto en esquina superior derecha

### ISSUE THREAD

**Issue by GonzaloUlla** [Jumpi96/helpo#90]
## Expected Behavior

Cuando clickeo en la fotito de arriba a la derecha, quiero ver quién soy
## Current Behavior

No tengo cómo saber quién soy sin entrar a consultar perfil

**Comment by LuchoGil** [comment]
Relacionada con issue #89.

**Comment by LuchoGil** [comment]
Muy bien Ju!
