### ISSUE TITLE
Mis Colaboraciones - Muestra grilla de voluntarios sin haber participado

### ISSUE THREAD

**Issue by JuliRios** [Jumpi96/helpo#96]
## Expected Behavior
En Mis Colaboraciones solo se muestran las grillas con los datos cargados de los materiales y/o funciones en las que efectivamente estoy colaborando.

## Current Behavior
Sin colaborar como voluntario, en Mis Colaboraciones se muestra la grilla de "Necesidades Voluntarios" tal cual como la cargó la ONG en un principio.

## Steps to Reproduce

1. Colaborar en un evento solo con necesidades materiales
2. Visualizar Mis Colaboraciones

**Comment by LuchoGil** [comment]
@JuliRios podes chequear si se puede cerrar esta Issue.
